### ISSUE TITLE
Support for Rocket async branch

### ISSUE THREAD

**Issue by grantperry** [lawliet89/rocket_cors#79]

**Comment by ELD** [comment]
@lawliet89 I noticed you mentioned that you're no longer using Rocket. Is this a project you would like to find another maintainer for to help out with? If so, I'd be happy to help out where I can, whether as a PR reviewer or a maintainer of the project!

**Comment by lawliet89** [comment]
@ELD Thank you for your offer. Do you have an email address or some form of instant messaging I could contact you to discuss this? I am open to having others to help with maintaining the project.

Sorry for the neglect. 🙏

**Comment by ELD** [comment]
@lawliet89 Yep! The email listed on my GitHub profile is a good one to contact me with. We can go from there and/or coordinate using some type of instant messaging service.

No worries about the neglect! Just figured since you mentioned no longer using Rocket that you could use some help to maintain this project! It's been useful for me in the past :)
